# Generated by Django 4.2.10 on 2024-03-21 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s3', '0002_alter_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='admin_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upload',
            name='user_comment',
            field=models.TextField(default=''),
        ),
    ]
