# Generated by Django 4.2.11 on 2024-04-03 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s3", "0003_upload_admin_comment_upload_status_upload_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (0, "Priority Not Selected"),
                    (1, "Lowest Priority"),
                    (2, "Low Priority"),
                    (3, "Moderate Priority"),
                    (4, "High Priority"),
                    (5, "Highest Priority"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="admin_comment",
            field=models.TextField(default="No comment yet"),
        ),
    ]
