# Generated by Django 3.2.25 on 2024-04-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0004_upload_created_at_upload_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.TextField(default='Report'),
        ),
    ]
