# Generated by Django 3.2.25 on 2024-04-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0005_upload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
